export default Object.freeze
(
	{
		ADD_ALERT_MESSAGE: "ADD_ALERT_MESSAGE",
		LANG_MESSAGE: "LANG_MESSAGE",
		SET_CURRENT_USER: "SET_CURRENT_USER",
		
		RESET_MRO_DATA: "RESET_MRO_DATA",
		CONVERT_MRO_FILE: "CONVERT_MRO_FILE",
		CONVERT_MRO_FILE_PENDING: "CONVERT_MRO_FILE_PENDING",
		CONVERT_MRO_FILE_FULFILLED: "CONVERT_MRO_FILE_FULFILLED",
		CONVERT_MRO_FILE_REJECTED: "CONVERT_MRO_FILE_REJECTED"
	}
);
