export const ADD_ALERT_MESSAGE = "ADD_ALERT_MESSAGE";
export const DELETE_ALERT_MESSAGE = "DELETE_ALERT_MESSAGE";
export const DELETE_ALL_ALERT_MESSAGES = "DELETE_ALL_ALERT_MESSAGES";
export const LANG_MESSAGE = "LANG_MESSAGE";